"""Ajustando relacionamento

Revision ID: 1b00675f9e20
Revises: becd051d0848
Create Date: 2025-11-20 22:30:40.067998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b00675f9e20'
down_revision = 'becd051d0848'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('revoked_tokens', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('revoked_tokens_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'usuario', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('revoked_tokens', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('revoked_tokens_ibfk_1'), 'usuario', ['user_id'], ['id'])

    # ### end Alembic commands ###
