"""empty message

Revision ID: 381814b4c245
Revises: cf993a9a5fc4
Create Date: 2025-12-17 20:28:17.446530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '381814b4c245'
down_revision = 'cf993a9a5fc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('folder',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['folder.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('folder_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'folder', ['folder_id'], ['id'])

    with op.batch_alter_table('usuario_provedor', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('usuario_provedor_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'usuario', ['usuario_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario_provedor', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('usuario_provedor_ibfk_1'), 'usuario', ['usuario_id'], ['id'])

    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('folder_id')

    op.drop_table('folder')
    # ### end Alembic commands ###
