"""Adicionando relacionamentos e FKs

Revision ID: 67f9be032ee0
Revises: d38892a2dfca
Create Date: 2025-11-17 17:15:36.483480

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '67f9be032ee0'
down_revision = 'd38892a2dfca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('revoked_tokens', schema=None) as batch_op:
        batch_op.drop_column('expires_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('revoked_tokens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expires_at', mysql.DATETIME(), nullable=False))

    # ### end Alembic commands ###
