"""Adicionando métodos de criação e verificação de tokens para redefinição de senha e confirmação de email

Revision ID: becd051d0848
Revises: 67f9be032ee0
Create Date: 2025-11-18 22:39:48.653410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'becd051d0848'
down_revision = '67f9be032ee0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('confirm_user', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('confirm_user')

    # ### end Alembic commands ###
