"""empty message

Revision ID: e0ff06a8764f
Revises: 1b00675f9e20
Create Date: 2025-11-29 22:40:26.374022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0ff06a8764f'
down_revision = '1b00675f9e20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('curso', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('biografia', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('biografia')
        batch_op.drop_column('curso')

    # ### end Alembic commands ###
